<a href="https://colab.research.google.com/github/ooootaaaa/DeepLearning2022Late/blob/main/0920%5B%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E7%94%A8%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュールを使う
##import文でモジュールを読み込んで使う
例) math

In [1]:
#mathモジュールを読み込む
import math
print(math.pi)#mathの中に定義してある円周率を表示
print(math.pow(5,2))#5の2乗
print(math.sqrt(9))#9の平方根

3.141592653589793
25.0
3.0


## Numpy -- 数値計算用の便利なライブラリ

https://numpy.org/


In [2]:
#numpy を import
import numpy as np

### numpy配列をつくる(ndarray)


In [3]:
#リストを引き渡してndarrayを作る
a = np.array([5,7,3,1,4,3])
print(a)

[5 7 3 1 4 3]


##Numpyで配列の操作をしてみる
配列を構成しなおす

In [4]:
#現在、aは1行1次元配列
print(a)
#aを3行2列の2次元配列に構成しなおす
b = a.reshape([3,2])#新しい配列の構成を引数で指定する
print(b)

[5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


###Numpy配列の中身を初期化しいて作る

In [5]:
#3行4列の0が入った2次元配列を作る
c = np.zeros((3,4))
print(c)
#ランダムな値が入った配列を作る
np.random.seed(0)
r = np.random.rand(3,4)
print(r)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


##Numpyのスライスのやり方
###基本
スライスの指定の仕方[start:stop:step]で指定する

In [6]:
#リストのスライス
l = list(range(10))#0～9までの10個の要素のリスト
print(l)
print(l[4:8])#[4:8]でスライス
print(l[::])#stepを-1でスライス

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


###1次元のNumpy配列(ndarray)におけるスライス

In [7]:
#範囲を指定してndarrayを作る
a = np.arange(10)#0～9の10個の要素のndarray
print(a)
print(a[2:8])
print(a[2:8:2])#step2で2個飛ばし
print(a[2:8:3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[2 5]


###1次元配列のndarrayのスライスに代入

In [8]:
print(a)
a[3:6]=100#指定した範囲に特定の値を代入
print(a)
a[3:6] = [100,200,300]#指定した範囲にリストの値を代入
print(a)
#a[3:6] = [100,200,300,400] #3つの範囲に4つの要素で上書きはできない
a = np.arange(10)
print(a)
a[2:8:2] = 100#start2stop8にstep2で上書き
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]
[  0   1   2 100 200 300   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]
[  0   1 100   3 100   5 100   7   8   9]


###多次元配列のndarrayのスライス

In [10]:
#3行4列の2次元配列を作る
a = np.arange(12).reshape((3,4))
print(a)
#2行目から終わりまでの行  =[1: ]
#2列名から4列目手前までの列 = [1:3]
print(a[1:, 1:3])
b = np.arange(20).reshape(5,4)
print(b)
#9,10 13,14 17,18 の3行2列だけ抜き出す
print(b[2:, 1:3])
c = b[2:, 1:3]
# スライスした部分が何行何列なのか
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 9 10]
 [13 14]
 [17 18]]
(3, 2)


###多次元のndarrayへのスライスでの代入

In [11]:
# 要素数12の3行4列の2次元配列を作る
a = np.arange(12).reshape(3,4)
print(a)
# 5,6,9,10の部分をスライス
print(a[1:, 1:3])
a[1:, 1:3] = 100
print(a)
a = np.arange(12).reshape(3,4)
# 多次元での上書きにリストを使う
a[1:, 1:3] = [100, 200]
print(a)
# 多次元の上書きに2次元のリストを使う
a[1:,1:3] = [[100, 200], [300, 400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 100 200  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


###多次元のnddarrayへのstepを使ったスライスでの代入

In [12]:
# 要素数12 3行4列のndarrayを作って変数aに代入
a = np.arange(12).reshape((3,4))
print(a)
# スライスにstepを使ってみる 4,6,8,10を抜き出す
print(a[1:, ::2])
#0,3,4,7 抜き出す
print(a[:2:, : :3])
a[1: , ::2] = 100
print(a)
#4,6,8,10だったところを100で上書き
a[1: , ::2] = [100,200]
print(a)
#4,6,8,10だったところを多次元リストで上書き
a[ 1: , ::2] = [[100,200], [300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[0 3]
 [4 7]]
[[  0   1   2   3]
 [100   5 100   7]
 [100   9 100  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [100   9 200  11]]
[[  0   1   2   3]
 [100   5 200   7]
 [300   9 400  11]]
